# Generated by Django 3.1.7 on 2021-03-19 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('place', models.CharField(max_length=100)),
                ('fine', models.IntegerField(default=500)),
                ('license_number', models.IntegerField()),
                ('vechile_number', models.IntegerField()),
                ('vechile_type', models.CharField(choices=[('BIKE', 'BIKE'), ('SCOOTER', 'SCOOTER'), ('CAR', 'CAR'), ('TRUCK', 'TRUCK'), ('BUS', 'BUS'), ('MINI VAN', 'MINI VAN')], default='BIKE', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
